/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-5-29 下午12:52' with Gradle 2.14
 *
 * @author Administrator, @date 17-5-29 下午12:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
